spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_run_openvidu
    username: root
    password: 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017/learn_run_openvidu

openvidu:
  url: http://localhost:5443/openvidu
  secret: MY_SECRET


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG  # MongoTemplate 쿼리 로그 출력
    root: INFO